version: "3.8"

services:
  app:
    container_name: app-dev-c
    image: app-idev-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    restart: unless-stopped

  server:
    container_name: app-dev-s
    image: app-idev-server
    build:
      context: ../cs_backend
      dockerfile: Dockerfile
    volumes:
      - ..cs_backend/src:/server/src
    depends_on:
      - app
    networks:
      - inventree
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  inventree:
    name: inventreeWEB
    external: true
